### ISSUE TITLE
Github pages needed

### ISSUE THREAD

**Issue by nipunattri1** [Vaansh-GitHub/Web-Development#1]
its recommended to enable github pages over this repo.
THNX

**Comment by Vaansh-GitHub** [comment]
Hmm,yaa I am thinking over this and when I will be free I will do that why not you contribute to this repo too!!

**Comment by Vaansh-GitHub** [comment]
> its recommended to enable github pages over this repo.
> THNX

Hmm,yaa I am thinking over this and when I will be free I will do that why not you contribute to this repo too!!

**Comment by nipunattri1** [comment]
Hello, I am Vaansh and this is my repository.
You can add some notes here then i will read them and merge them and can know your request.Like this,
Vaansh:"This is Web Development tutorials cum practice."
Your_name:"message"


Just change the word "c*m" from there😅
